[WIP] vega down & destroy
srijanone/vega pull request #134
Opened 2020-08-10 06:10 UTC by WSMathias

2020-08-10 06:28 UTC, vs4vijay reviewed
1 suggestion, rest looks okay to me.

Also @WSMathias Please update the README as well as per new changes and commands

2020-08-10 06:28 UTC, vs4vijay commented on cmd/up.go
> +func isDrupal() bool {
Maybe put this method in some `Detector` package

2020-08-10 07:09 UTC, WSMathias commented on cmd/up.go
> +func isDrupal() bool {
sure, I will add  Detector package.

2020-08-12 08:55 UTC, AshishThakur commented on cmd/destroy.go
> +	downCmd := &cobra.Command{
@WSMathias I see down cmd already defined in down.go, would this command be destroy?

2020-08-12 11:43 UTC, mountain-nerd requested changes
@WSMathias please make relevant changes in destroy.go

2020-08-12 11:43 UTC, mountain-nerd commented on cmd/destroy.go
> +	downCmd := &cobra.Command{
Am i mssing something?

2020-08-12 11:47 UTC, merged